-- DropForeignKey
ALTER TABLE "GEO_DATA" DROP CONSTRAINT "GEO_DATA_userId_fkey";

-- AlterTable
ALTER TABLE "GEO_DATA" ALTER COLUMN "userId" DROP NOT NULL,
ALTER COLUMN "fileContent" DROP NOT NULL;

-- AddForeignKey
ALTER TABLE "GEO_DATA" ADD CONSTRAINT "GEO_DATA_userId_fkey" FOREIGN KEY ("userId") REFERENCES "USERS"("id") ON DELETE SET NULL ON UPDATE CASCADE;
